import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const root = path.join(process.cwd(),'content','blog');
const posts = [];
for (const lang of ['zh','en']) {
  const dir = path.join(root,lang);
  if (!fs.existsSync(dir)) continue;
  for (const file of fs.readdirSync(dir).filter(name => name.endsWith('.md'))) {
    const slug = file.replace(/\.md$/,'');
    const parsed = matter(fs.readFileSync(path.join(dir,file),'utf8'));
    posts.push({
      slug, lang,
      title: String(parsed.data.title ?? slug),
      date: String(parsed.data.date ?? ''),
      excerpt: String(parsed.data.excerpt ?? ''),
      tags: Array.isArray(parsed.data.tags) ? parsed.data.tags.map(String) : [],
      source: parsed.data.source ? String(parsed.data.source) : undefined,
      sourceType: parsed.data.sourceType ? String(parsed.data.sourceType) : undefined,
      zhihuId: parsed.data.zhihuId ? String(parsed.data.zhihuId) : undefined,
      translationStatus: parsed.data.translationStatus ? String(parsed.data.translationStatus) : undefined,
      content: parsed.content,
    });
  }
}
posts.sort((a,b) => b.date.localeCompare(a.date));
const output = `// Generated by scripts/build-content.mjs. Do not edit by hand.\nexport const generatedPosts = ${JSON.stringify(posts,null,2)} as const;\n`;
fs.writeFileSync(path.join(process.cwd(),'lib','generated-posts.ts'),output,'utf8');
console.log(`Indexed ${posts.length} blog post(s).`);
